import React from 'react'

const Footer = () => {
  return (
    <div style={{marginTop:"50px"}}>
     <h3>Fashion World -  WOMEN’S LUXURY AND DESIGNER FASHION</h3>
     <p>Mytheresa is the most-trusted source for finding the finest selection of luxurious womenswear. Our expert buying team travels the globe with a simple mission: to bring international fashion’s finest directly to your doorstep. With our runway-fresh new arrivals every week, an easy-to-navigate platform and a mobile app to shop on-the-go, we ensure a boutique-like feeling for a unique shopping experience.</p>   
     <div style={{display:"grid" ,gridTemplateColumns:'50% 50%',gap:"10px"}} ><div><h5>A Luxury Shopping Experience</h5> <ul><li>The finest edit of more than 200 international luxury brands</li><li>900 new arrivals each week directly from the runway</li><li>Well-curated selection of items for a boutique-like shopping experience</li><li>Exclusive designer collaborations and capsule collections that you won’t find anywhere else
</li></ul>   </div> <div><h5>Service And Quality</h5> <ul><li>The finest edit of more than 200 international luxury brands</li><li>900 new arrivals each week directly from the runway</li><li>Well-curated selection of items for a boutique-like shopping experience</li><li>Exclusive designer collaborations and capsule collections that you won’t find anywhere else
</li></ul>  </div> <p>Whether you are looking for the latest Bottega Veneta pouch for everyday wear, Jimmy Choo heels for an upcoming wedding, or a Burberry scarf to gift a friend, our edit comprises the key pieces that you need for an elegant season ahead. With our assortment of timeless items and exclusive capsule collections, which includes everything from the understated luxury of Loro Piana and avant-garde appeal of Maison Margiela, to Saint Laurent bags and time-honored Gucci loafers; you are certain to find everything you want to build your dream closet.</p> <p>Get inspired by our coveted edit, which makes occasion dressing easy by breaking down our buy into easy-to-shop categories such as fashion sneakers or exquisite gowns. Delve into our exclusive selection of designer must-haves. Our exceptional customer service team is here to help you through every step of the order process, and beyond, to make sure you start every day dressed to conquer.</p>  </div> <hr/>
 <h2>Shop whenever Wherever With The App</h2>  
 <div style={{display:"grid" ,gridTemplateColumns:'50% 50%',gap:"10px"}}><div> <img style={{width:'100px',marginLeft:"400px",marginTop:"-10px"}} src='https://www.svgrepo.com/show/303128/download-on-the-app-store-apple-logo.svg' alt='https://www.svgrepo.com/show/303128/download-on-the-app-store-apple-logo.svg' /> </div> <div> <img style={{width:'120px',marginRight:'400px'}} src='https://www.logo.wine/a/logo/Google_Play/Google_Play-Badge-Logo.wine.svg' alt='https://www.logo.wine/a/logo/Google_Play/Google_Play-Badge-Logo.wine.svg' /></div></div>
 <hr/>
 <div style={{display:'grid',gridTemplateColumns:'30% 20% 20% 30%',gap:"10px"}} > <div><p>Service & Security</p> <div style={{marginTop:"10px"}}><h5>Fast Delivery</h5><p>Delivery Within 2 Business Days</p> </div> <div style={{marginTop:"10px"}}><h5>Free Returns Within 20 Days</h5><p>Convenient return Policy</p> </div><div style={{marginTop:"10px"}}><h5>Secure Payment And Data Protection</h5><p>SSL encryption for faster transactions and secure data</p> </div> </div> <div><p>Fashion World</p> <p>About Us</p><p>Trust & Services</p><p>Sustainability</p> <p>Press</p><p>Careers</p><p>Investor Relation</p><p>Affiliates</p><p>Tax-Free Shopping</p></div> <div> <p>Customer Care </p> <p>Contact Us</p> <p>Shipping information</p><p>Secure Payment</p> <p>Exchanges</p><p>Returns</p><p>After sale service</p><p>Gift Card</p></div> <div><p>GET TREND UPDATES, STYLE TIPS AND MORE</p> <div style={{display:"flex"}} ><input placeholder='Your email address here...' /><button>Sign up</button></div> <h4>Wish List</h4> <p>Receive personal notifications</p> <h4>Follow us on</h4>  <img style={{width:"60%"}} src="https://icon-library.com/images/facebook-and-twitter-icon/facebook-and-twitter-icon-7.jpg" alt="https://e7.pngegg.com/pngimages/921/1023/png-clipart-facebook-twitter-and-instagram-logo-social-media-facebook-computer-icons-social-networking-service-like-us-on-facebook-text-logo.png" /> </div>  </div>
 <hr/>
 <div style={{display:"flex"}}><p>Payment Methods</p> <img  style={{width:"30%" ,height:"50px"}}src="https://help.zazzle.com/hc/article_attachments/360023193074/payment_Capture.JPG" alt="https://t4.ftcdn.net/jpg/04/55/10/23/360_F_455102361_RsJAeKOVlrrbvLLRtrFQ3K6VAuDg0b4b.jpg" /></div>
    </div>
  )
}

export default Footer
